name: Respond

on: [repository_dispatch]
 
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/dgounaris/test-jira-actions/dispatches \
          --data '{"event_type": "pong", "client_payload": { }}'
